INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (117, N'交易查询', N'menu', N'', 115, N'', N'transaction:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (1, N'资源', N'menu', N'#', 0, N'0/', N'#', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (118, N'供应查询', N'menu', N'', 115, N'', N'supply:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (119, N'多点存量', N'menu', N'', 115, N'', N'manypoint:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (120, N'单点存量', N'menu', N'', 115, N'', N'onepoint:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (122, N'项目土地', N'menu', N'', 115, N'', N'project:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (124, N'成交排行', N'menu', N'', 123, N'', N'makes:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (125, N'供应排行', N'menu', N'', 123, N'', N'supplier:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (127, N'土地查询', N'menu', N'', 1, N'', N'land:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (128, N'土地查询', N'menu', N'', 127, N'', N'tudi:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (130, N'土地整理', N'menu', N'', 127, N'', N'tudi3:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (132, N'信息采集', N'menu', N'', 127, N'', N'message:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (133, N'个性设置', N'menu', N'', 1, N'', N'individuation:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (135, N'单价段定义', N'menu', N'settingAction/housesList', 133, N'', N'price:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (137, N'楼盘组群', N'menu', N'', 133, N'', N'housesgroup:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (138, N'小微板块', N'menu', N'', 133, N'', N'xiaowei:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (140, N'户型定义', N'menu', N'', 133, N'', N'housesmodel:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (142, N'物业定义', N'menu', N'', 133, N'', N'estates:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (143, N'销售状态', N'menu', N'', 133, N'', N'sales:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (145, N'所属区域', N'menu', N'', 133, N'', N'ownerarea:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (147, N'建筑类型', N'menu', N'', 133, N'', N'building:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (61, N'用户组管理', N'menu', N'groupAction/permissionAssignment', 148, N'0/1/', N'admin:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (62, N'to添加用户组', N'button', NULL, 61, N'0/1/61', N'admin:group:toAdd', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (63, N'添加用户组', N'button', NULL, 61, N'0/1/61/', N'admin:group:doAdd', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (64, N'to修改用户组', N'button', NULL, 61, N'0/1/61/', N'admin:group:toUpdate', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (65, N'修改用户组', N'button', NULL, 61, N'0/1/61/', N'admin:group:doUpdate', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (71, N'用户管理', N'menu', N'userAction/userDatagrid', 148, N'0/1/', N'admin:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (72, N'to添加用户', N'button', NULL, 71, N'0/1/71/', N'admin:user:toAdd', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (73, N'添加用户', N'button', NULL, 71, N'0/1/71/', N'admin:user:doAdd', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (74, N'to修改用户', N'button', NULL, 71, N'0/1/71/', N'admin:user:toUpdate', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (75, N'修改用户', N'button', NULL, 71, N'0/1/71/', N'admin:user:doUpdate', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (100, N'在线用户', N'menu', N'userAction/toListOnlineUser', 148, N'0/1/', N'admin:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (101, N'踢出用户', N'button', NULL, 100, N'0/1/100/', N'admin:session:forceLogout', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (108, N'同步用户', N'button', NULL, 71, N'0/1/71/', N'admin:user:syncUser', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (111, N'资源管理', N'menu', N'resourceAction/toList', 148, N'0/1/', N'admin:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (115, N'商品房信息', N'menu', N'#', 1, N'0', N'house:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (116, N'项目查询', N'menu', N'#', 115, N'1', N'house:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (121, N'坐标设置', N'menu', N'', 115, N'', N'coordinate:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (123, N'楼市榜单', N'menu', N'', 1, N'', N'market:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (126, N'存量排行', N'menu', N'', 123, N'', N'stock:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (129, N'土地录入', N'menu', N'', 127, N'', N'tudi2:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (131, N'坐标检查', N'menu', N'', 127, N'', N'coordinate:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (134, N'面积段定义', N'menu', N'', 133, N'', N'area:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (136, N'总价段定义', N'menu', N'', 133, N'', N'totalprice:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (139, N'所属板块', N'menu', N'', 133, N'', N'unders:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (141, N'交付标准', N'menu', N'', 133, N'', N'deliverys:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (144, N'交易状态', N'menu', N'', 133, N'', N'transactions:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (146, N'地图设置', N'menu', N'', 133, N'', N'mapset:*', 1); GO
INSERT INTO [t_resource]([id], [name], [type], [url], [parent_id], [parent_ids], [permission], [available]) VALUES (148, N'系统设置  ', N'menu', N'', 1, N'', N'sysconfig:*', 1); GO
